### PR TITLE
Update HomeAnimation.vue

### PR DESCRIPTION
**Pull request by neshvig10**
added link to "Learn more about Basic Income"

### CODE REVIEW

**Comment by neshvig10** [comment]
Fixed the issues

**Comment by SebinSong** [comment]
duplicate of #71

**Comment by taoeffect** [comment]
Hi @neshvig10! Thanks for sending in this PR, but yeah [Sebin was working on it](https://github.com/okTurtles/groupincome.org/issues/69#issuecomment-1623170593).

If you'd like to help contribute to the project, feel free to comment on an unassigned issue to let us know what you're interested in working on, and then once I've made sure it's an open issue I can assign it to you. ^_^

**Comment by neshvig10** [comment]
> Hi @neshvig10! Thanks for sending in this PR, but yeah [Sebin was working on it](https://github.com/okTurtles/groupincome.org/issues/69#issuecomment-1623170593).
> 
> If you'd like to help contribute to the project, feel free to comment on an unassigned issue to let us know what you're interested in working on, and then once I've made sure it's an open issue I can assign it to you. ^_^

I have fixed this issue and made a PR 😀
But it was closed by Sebin

**Comment by taoeffect** [comment]
@neshvig10 Your PR was closed because Sebin was already assigned to fix issue #69. You [acknowledged this](https://github.com/okTurtles/groupincome.org/issues/69#issuecomment-1623171759) but sent in a PR anyway for some reason.

**Comment by neshvig10** [comment]
> @neshvig10 Your PR was closed because Sebin was already assigned to fix issue #69. You [acknowledged this](https://github.com/okTurtles/groupincome.org/issues/69#issuecomment-1623171759) but sent in a PR anyway for some reason.

Yeah , sorry for that .

**Pull request closed without merging**
