### PR TITLE
#89 Add a new blog post, #92 Two footnotes related issues

### LINKED ISSUE #89: Add latest blog post
### Problem

This post isn't on the new site: https://groupincome.org/2023/06/the-prototype-is-ready/

### Solution

You can find the markdown for the post here: https://gitlab.okturtles.org/okturtles/groupincome-blog/-/blob/master/2023-prototype-ready.md

Add this post to the updated blog.

### LINKED ISSUE #92: Two footnote related issues
### Problem

Screenshot 2024-03-07 at 5 05 41 PM

1. When clicking the arrow icon to return to where the footnote was, it doesn't work.
2. There should be a horizontal divider creating a special footnote section when footnotes exist. See the old blog for an example, here's a screenshot:

Screenshot 2024-03-07 at 5 06 47 PM

### Solution

Address these two issues.

### PR DESCRIPTION
**Pull request by SebinSong**
closes #89 
closes #92 

Would you maybe want to add an image to this blog post too?
Currently it doesn't have an image which make it looks like below screenshots

**[ In the page itself ]**

**[ In the blog list ]**

Please let me know if there is an image you want to use there.

Cheers,

### CODE REVIEW

**Review by taoeffect — CHANGES_REQUESTED** [review]
To answer your question: feel free to use a screenshot of the app itself as the image. Perhaps make a demo group locally.

I also noticed that the old blog post is making use of a WordPress plugin that uses `[note]...[/note]` syntax to create special footnotes:

Screenshot 2024-03-06 at 6 45 11 PM

Could you please convert these to use Markdown-based footnotes? (You can have a look at some of the May's Theorem blog posts for how to do that if unsure).

**Review by taoeffect — COMMENTED** [review]
Per Slack, it sounds like #92 will be incorporated into this PR as well

**Comment by SebinSong** [comment]
@taoeffect Updated the PR with the work for #92



Also, while working on the issue, it occured to me that it would be a good idea to make the header image of this particular blog post slightly blended like below screenshot (thought it would look better than it having solid edges).



But if you prefer the solid edge, I will revert this change back.

Thanks,

**Review by taoeffect — CHANGES_REQUESTED** [review]
Nice job @SebinSong, the footnotes are looking great in the footer! 👍 

While testing, I noticed that there was an issue with the rendering of the sentences with footnotes:

Screenshot 2024-03-11 at 5 55 38 PM

It should look like this:

Screenshot 2024-03-11 at 5 55 58 PM

BTW -  I think the screenshot you took looks great! Well done!

While we're still making changes on this, I would like to make one more request with respect to that: can you see if you can add a nice drop-shadow effect to the image? I think it would look nicer with it.

**Comment by SebinSong** [comment]
@taoeffect 
Just made another update to the PR!

1. That was a caveat of the solution which requires adding `display: block;` to the anchor tag's pseudo element which doesn't work for our cases. So I entirely updated the solution to the way where adding customised `click` handlers to all footnote related `<a />` tags in the articles.

2. Added a box shadow to the blog post image. hope it looks good to you and pls note that this effect is applied uniformly to all blog post pages.

**Comment by SebinSong** [comment]
@taoeffect 

I visited https://vitejs.dev/ website yesterday and thought the coloured gradient shadow in there looked cool.



so I went ahead and tried creating the similar effect to the blog post images using group income logo theme colors like below.



Let me know if your prefer the grey coloured drop-shadow though. (To me, it feels like when the image itself is too colourful, the shadow doesn't feel as nice)

Thanks,

**Comment by taoeffect** [comment]
@SebinSong while the fact that it's possible to create such gradients is really cool, I'll be honest, to my eye it looks way better the way it did, with the black shadow

**Review by taoeffect — APPROVED** [review]
Fantastic work @SebinSong! 👏

**Pull request merged**
